# Generated by Django 5.1.1 on 2026-01-19 09:04

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_verified_email'),
        ('listings', '0002_uav'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('boosted', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_analytics', to='listings.listing')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['listing'], name='analytics_l_listing_4103ae_idx'), models.Index(fields=['date_created'], name='analytics_l_date_cr_4b5354_idx'), models.Index(fields=['impressions'], name='analytics_l_impress_aebcc0_idx'), models.Index(fields=['boosted'], name='analytics_l_boosted_5dbfa5_idx')],
                'unique_together': {('listing', 'date_created')},
            },
        ),
        migrations.CreateModel(
            name='MechanicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('boosted', models.BooleanField(default=False)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_analytics', to='accounts.mechanic')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['mechanic'], name='analytics_m_mechani_2f7a8f_idx'), models.Index(fields=['date_created'], name='analytics_m_date_cr_bf9da0_idx'), models.Index(fields=['impressions'], name='analytics_m_impress_c0442f_idx'), models.Index(fields=['boosted'], name='analytics_m_boosted_3af09b_idx')],
                'unique_together': {('mechanic', 'date_created')},
            },
        ),
    ]
