# Generated by Django 5.1.1 on 2025-02-26 09:40

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Vehicle Categories",
            },
        ),
        migrations.CreateModel(
            name="VehicleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("seats", "Seats"),
                            ("doors", "Doors"),
                            ("drivetrain", "Drivetrain"),
                            ("engine", "Engine"),
                            ("parking-assistant", "Parking Assistant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                ("value", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("issuer", models.CharField(default="dealership", max_length=20)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("discount_type", models.CharField(default="flat", max_length=20)),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
                ),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("users", models.ManyToManyField(blank=True, to="accounts.customer")),
                (
                    "valid_in",
                    models.ManyToManyField(blank=True, to="accounts.dealership"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("rental", "Car Rental"), ("sale", "Car Sale")],
                        default="sale",
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10000, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=400, null=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                (
                    "payment_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "Daily Payments"),
                            ("week", "Weekly Payments"),
                            ("month", "Monthly Payments"),
                            ("year", "Annual Payments"),
                        ],
                        default="week",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"user_type": "customer"},
                        related_name="viewers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("rental", "Car Rental"), ("sale", "Car Sale")],
                        max_length=20,
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[("rental", "Car Rental"), ("sale", "Car Sale")],
                        default="Not Available",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("awaiting-inspection", "Awaiting Inspection"),
                            ("inspecting", "Inspecting"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("renewed", "Renewed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "payment_cycle",
                    models.CharField(
                        choices=[
                            ("day", "Daily Payments"),
                            ("week", "Weekly Payments"),
                            ("month", "Monthly Payments"),
                            ("year", "Annual Payments"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                ("rent_from", models.DateField(blank=True, null=True)),
                ("rent_until", models.DateField(blank=True, null=True)),
                ("last_payment", models.DateField(blank=True, null=True)),
                ("next_payment", models.DateField(blank=True, null=True)),
                (
                    "applied_coupons",
                    models.ManyToManyField(blank=True, to="listings.coupon"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarRental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listings.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="listings.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10000)),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bidder",
                        to="accounts.customer",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="offers",
            field=models.ManyToManyField(
                blank=True, related_name="offers", to="listings.purchaseoffer"
            ),
        ),
        migrations.CreateModel(
            name="TestDriveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("granted", models.BooleanField(default=False)),
                ("testdrive_complete", models.BooleanField(default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "requested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.dealership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="testdrives",
            field=models.ManyToManyField(
                blank=True, related_name="testdrives", to="listings.testdriverequest"
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True)),
                ("color", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used_uk", "Used (UK)"),
                            ("used_ng", "Used (Nigerian)"),
                            ("used_be", "Used (Belgium)"),
                        ],
                        default="used_uk",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sedan", "Sedan"),
                            ("convertible", "Convertible"),
                            ("suv", "Sub-Urban Vehicle"),
                            ("truck", "Truck"),
                        ],
                        default="sedan",
                        max_length=200,
                    ),
                ),
                ("mileage", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "fuel_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("petrol", "Petrol"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "drivetrain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("4WD", "Four Wheel Drive"),
                            ("AWD", "All Wheel Drive"),
                            ("FWD", "Front Wheel Drive"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(blank=True, default=5, null=True),
                ),
                (
                    "doors",
                    models.PositiveIntegerField(blank=True, default=4, null=True),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("petrol", "Petrol"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="vehicles/videos/"
                    ),
                ),
                ("custom_duty", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=True)),
                ("for_sale", models.BooleanField(default=False)),
                ("for_rent", models.BooleanField(default=False)),
                ("sold", models.BooleanField(default=False)),
                (
                    "current_rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_rental",
                        to="listings.carrental",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dealer",
                        to="accounts.dealership",
                    ),
                ),
                (
                    "last_rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_rental",
                        to="listings.carrental",
                    ),
                ),
                (
                    "rentals",
                    models.ManyToManyField(
                        blank=True, related_name="rentals", to="listings.carrental"
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vehicle_features",
                        to="listings.vehiclefeature",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=10000),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.dealership",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.vehicle"
            ),
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=utils.make_UUID)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="vehicles/images/")),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.vehicle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="listings.vehicleimage"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="tags",
            field=models.ManyToManyField(blank=True, to="listings.vehicletag"),
        ),
    ]
