# Generated by Django 5.1.1 on 2025-01-28 08:53

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='VehicleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('listing_type', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], default='sale', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('payment_cycle', models.CharField(blank=True, choices=[('weekly', 'Weekly Payments'), ('bi-weekly', 'Bi-Weekly Payments'), ('monthly', 'Monthly Payments'), ('bi-monthly', 'Bi-Monthly Payments'), ('quarterly', 'Quarterly Payments'), ('semi-annually', 'Semi-Annual Payments'), ('annually', 'Annual Payments')], default='monthly', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'customer'}, related_name='viewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], max_length=20)),
                ('payment_option', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], default='Not Available', max_length=20)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('car', 'Car'), ('service', 'Service'), ('rental', 'Rental')], default='car', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customercart')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.serviceoffering')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='listings.orderitem'),
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='accounts.customer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='offers', to='listings.purchaseoffer'),
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('testdrive_complete', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dealer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='testdrives',
            field=models.ManyToManyField(blank=True, related_name='testdrives', to='listings.testdriverequest'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used_uk', 'Used (UK)'), ('used_ng', 'Used (Nigerian)'), ('used_be', 'Used (Belgium)')], default='used_uk', max_length=20)),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('convertible', 'Convertible'), ('suv', 'Sub-Urban Vehicle'), ('truck', 'Truck')], default='sedan', max_length=200)),
                ('mileage', models.CharField(blank=True, max_length=200, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=200, null=True)),
                ('fuel_system', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('Electric', 'Electric'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid')], max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='vehicles/videos/')),
                ('custom_duty', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('for_sale', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('current_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_rental', to='listings.carrental')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer', to='accounts.dealer')),
                ('last_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rental', to='listings.carrental')),
                ('rentals', models.ManyToManyField(blank=True, related_name='rentals', to='listings.carrental')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicles/images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='listings.vehicleimage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='listings.vehicletag'),
        ),
    ]
