# Generated by Django 5.1.1 on 2025-12-04 10:30

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import utils
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used-foreign', 'Foreign Used'), ('used-local', 'Local Used')], default='used-foreign', max_length=20)),
                ('fuel_system', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('electric', 'Electric'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid')], max_length=200, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=200, null=True)),
                ('color', models.CharField(max_length=200)),
                ('mileage', models.CharField(blank=True, max_length=200, null=True)),
                ('for_sale', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='vehicles/videos/')),
                ('tags', utils.models.ArrayField(blank=True, default=list, null=True)),
                ('features', utils.models.ArrayField(blank=True, default=list, null=True)),
                ('custom_duty', models.BooleanField(default=False)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vehicles', to='accounts.dealership')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BoostPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('duration_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per duration unit', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Boost Pricing',
                'verbose_name_plural': 'Boost Pricing',
                'ordering': ['duration_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], max_length=20)),
                ('payment_option', models.CharField(choices=[('pay-after-inspection', 'Payment after Inspection'), ('wallet', 'Veyu Wallet'), ('card', 'Credit / Debit Card'), ('financial-aid', 'Financing Aid')], default='pay-after-inspection', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('awaiting-inspection', 'Awaiting Inspection'), ('inspecting', 'Inspecting'), ('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, help_text='Platform service fee as percentage (e.g., 2.00 for 2%)', max_digits=5)),
                ('service_fee_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed service fee amount in NGN (added to percentage)', max_digits=10)),
                ('inspection_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Inspection fee as percentage of listing price (e.g., 5.00 for 5%)', max_digits=5)),
                ('inspection_fee_minimum', models.DecimalField(decimal_places=2, default=10000, help_text='Minimum inspection fee in NGN', max_digits=10)),
                ('inspection_fee_maximum', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum inspection fee in NGN (0 for no limit)', max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=7.5, help_text='Tax percentage (e.g., 7.5 for 7.5% VAT)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Platform Fee Settings',
                'verbose_name_plural': 'Platform Fee Settings',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.vehicle')),
                ('engine_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('bike_type', models.CharField(blank=True, choices=[('cruiser', 'Cruiser'), ('sport', 'Sport'), ('touring', 'Touring'), ('offroad', 'Off-Road')], max_length=50, null=True)),
                ('saddle_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.vehicle',),
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.vehicle')),
                ('hull_material', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_count', models.PositiveIntegerField(blank=True, null=True)),
                ('propeller_type', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('beam_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('draft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.vehicle',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.vehicle')),
                ('doors', models.PositiveIntegerField(blank=True, default=4, null=True)),
                ('seats', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('drivetrain', models.CharField(blank=True, choices=[('4WD', 'Four Wheel Drive'), ('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], max_length=200, null=True)),
                ('vin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.vehicle',),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.vehicle')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_type', models.CharField(blank=True, choices=[('jet', 'Jet'), ('propeller', 'Propeller'), ('glider', 'Glider'), ('helicopter', 'Helicopter')], max_length=50, null=True)),
                ('max_altitude', models.PositiveIntegerField(blank=True, null=True)),
                ('wing_span', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('range', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.vehicle',),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('issuer', models.CharField(default='dealership', max_length=20)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(default='flat', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='available_coupons', to='accounts.customer')),
                ('valid_in', models.ManyToManyField(blank=True, related_name='valid_coupons', to='accounts.dealership')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('listing_type', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], default='sale', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('payment_cycle', models.CharField(blank=True, choices=[('single', 'One Time / Single Payment'), ('day', 'Daily Payments'), ('week', 'Weekly Payments'), ('month', 'Monthly Payments'), ('year', 'Annual Payments')], default='week', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_listings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_listings', to='listings.vehicle')),
                ('viewers', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'customer'}, related_name='viewed_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ListingBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('duration_count', models.PositiveIntegerField(default=1, help_text='Number of duration units (e.g., 2 weeks)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_boosts', to='accounts.dealership')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_boost', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Listing Boost',
                'verbose_name_plural': 'Listing Boosts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.order')),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.order',),
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.order')),
                ('is_recurring', models.BooleanField(default=False)),
                ('payment_cycle', models.CharField(choices=[('single', 'One Time / Single Payment'), ('day', 'Daily Payments'), ('week', 'Weekly Payments'), ('month', 'Monthly Payments'), ('year', 'Annual Payments')], default='month', max_length=20)),
                ('rent_from', models.DateField(blank=True, null=True)),
                ('rent_until', models.DateField(blank=True, null=True)),
                ('last_payment', models.DateField(blank=True, null=True)),
                ('next_payment', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rental Order',
                'verbose_name_plural': 'Rental Orders',
                'ordering': ['-date_created'],
            },
            bases=('listings.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupons',
            field=models.ManyToManyField(blank=True, related_name='coupon_orders', to='listings.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_orders', to='listings.listing'),
        ),
        migrations.CreateModel(
            name='OrderInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_time', models.TimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_inspections', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='listings.order')),
            ],
            options={
                'verbose_name': 'Order Inspection',
                'verbose_name_plural': 'Order Inspections',
                'ordering': ['inspection_date', 'inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers', to='accounts.customer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Purchase Offer',
                'verbose_name_plural': 'Purchase Offers',
                'ordering': ['-amount', '-date_created'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='listing_offers', to='listings.purchaseoffer'),
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('granted', models.BooleanField(default=False)),
                ('testdrive_complete', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdrive_requests', to='listings.listing')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdrive_requests', to='accounts.customer')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_testdrive_requests', to='accounts.dealership')),
            ],
            options={
                'verbose_name': 'Test Drive Request',
                'verbose_name_plural': 'Test Drive Requests',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='testdrives',
            field=models.ManyToManyField(blank=True, related_name='listing_testdrives', to='listings.testdriverequest'),
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradein_requests', to='accounts.customer')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tradein_requests', to='accounts.dealership')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradein_requests', to='listings.vehicle')),
            ],
            options={
                'verbose_name': 'Trade-in Request',
                'verbose_name_plural': 'Trade-in Requests',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='listings.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='vehicle_gallery', to='listings.vehicleimage'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='listings_co_code_bd6f08_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['issuer'], name='listings_co_issuer_436b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expires'], name='listings_co_expires_71c836_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['discount_type'], name='listings_co_discoun_a0c9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='listingboost',
            index=models.Index(fields=['listing'], name='listings_li_listing_044ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='listingboost',
            index=models.Index(fields=['dealer'], name='listings_li_dealer__f6b2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='listingboost',
            index=models.Index(fields=['start_date', 'end_date'], name='listings_li_start_d_e482df_idx'),
        ),
        migrations.AddIndex(
            model_name='listingboost',
            index=models.Index(fields=['active'], name='listings_li_active_15eb42_idx'),
        ),
        migrations.AddIndex(
            model_name='listingboost',
            index=models.Index(fields=['payment_status'], name='listings_li_payment_027426_idx'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_rental_vehicle', to='listings.rentalorder'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_rental_vehicle', to='listings.rentalorder'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rentals',
            field=models.ManyToManyField(blank=True, related_name='rental_vehicles', to='listings.rentalorder'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['is_recurring'], name='listings_re_is_recu_88c7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['payment_cycle'], name='listings_re_payment_681152_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['rent_from', 'rent_until'], name='listings_re_rent_fr_9b7d30_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['next_payment'], name='listings_re_next_pa_fbfce3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='listings_or_custome_041b72_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='listings_or_order_t_e1afef_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='listings_or_order_s_a47c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid'], name='listings_or_paid_8a5dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_created'], name='listings_or_date_cr_e742c5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_item'], name='listings_or_order_i_defe0f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinspection',
            index=models.Index(fields=['order'], name='listings_or_order_i_8f4b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinspection',
            index=models.Index(fields=['customer'], name='listings_or_custome_1c47ef_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinspection',
            index=models.Index(fields=['inspection_date'], name='listings_or_inspect_52f11a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderinspection',
            index=models.Index(fields=['completed'], name='listings_or_complet_38f1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseoffer',
            index=models.Index(fields=['bidder'], name='listings_pu_bidder__3b463a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseoffer',
            index=models.Index(fields=['listing'], name='listings_pu_listing_080985_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseoffer',
            index=models.Index(fields=['amount'], name='listings_pu_amount_0453b4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseoffer',
            index=models.Index(fields=['date_created'], name='listings_pu_date_cr_5565ef_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['requested_by'], name='listings_te_request_377471_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['requested_to'], name='listings_te_request_eeb062_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['listing'], name='listings_te_listing_264856_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['granted'], name='listings_te_granted_90f5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['testdrive_complete'], name='listings_te_testdri_e1836c_idx'),
        ),
        migrations.AddIndex(
            model_name='testdriverequest',
            index=models.Index(fields=['date_created'], name='listings_te_date_cr_a45513_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type'], name='listings_li_listing_f8edcf_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['verified', 'approved'], name='listings_li_verifie_6ac271_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_by'], name='listings_li_created_e252fa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['vehicle'], name='listings_li_vehicle_4a97fe_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['date_created'], name='listings_li_date_cr_765091_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['title'], name='listings_li_title_6ba558_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['customer'], name='listings_tr_custome_79049b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['to'], name='listings_tr_to_id_be7625_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['vehicle'], name='listings_tr_vehicle_f113b6_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['estimated_value'], name='listings_tr_estimat_595992_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeinrequest',
            index=models.Index(fields=['date_created'], name='listings_tr_date_cr_be0567_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle'], name='listings_ve_vehicle_3b1423_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealer'], name='listings_ve_dealer__5df859_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='listings_ve_brand_b2d0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['condition'], name='listings_ve_conditi_53f6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['fuel_system'], name='listings_ve_fuel_sy_a9b1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['transmission'], name='listings_ve_transmi_2bcef9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['for_sale', 'for_rent'], name='listings_ve_for_sal_e2b869_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['available'], name='listings_ve_availab_15e3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['slug'], name='listings_ve_slug_f23934_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['date_created'], name='listings_ve_date_cr_f19842_idx'),
        ),
    ]
