# Generated by Django 5.1.1 on 2026-01-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.vehicle')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('uav_type', models.CharField(blank=True, choices=[('quadcopter', 'Quadcopter'), ('hexacopter', 'Hexacopter'), ('octocopter', 'Octocopter'), ('fixed-wing', 'Fixed-Wing'), ('hybrid', 'Hybrid VTOL')], max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('recreational', 'Recreational'), ('photography', 'Photography/Videography'), ('surveying', 'Surveying/Mapping'), ('agriculture', 'Agriculture'), ('delivery', 'Delivery'), ('inspection', 'Industrial Inspection'), ('racing', 'Racing'), ('military', 'Military/Defense')], max_length=50, null=True)),
                ('max_flight_time', models.PositiveIntegerField(blank=True, null=True)),
                ('max_range', models.PositiveIntegerField(blank=True, null=True)),
                ('max_altitude', models.PositiveIntegerField(blank=True, null=True)),
                ('max_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('camera_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rotor_count', models.PositiveIntegerField(blank=True, null=True)),
                ('has_obstacle_avoidance', models.BooleanField(default=False)),
                ('has_gps', models.BooleanField(default=True)),
                ('has_return_to_home', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('listings.vehicle',),
        ),
    ]
