# Generated by Django 5.1.1 on 2026-01-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_uav'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup Truck'), ('van', 'Van/Minivan'), ('wagon', 'Wagon'), ('luxury', 'Luxury'), ('sport', 'Sports Car')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira'), ('USD', 'Dollar')], default='NGN', max_length=3),
        ),
    ]
