# Generated by Django 5.1.1 on 2024-09-13 09:29

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('chat_source', models.CharField(choices=[('chat', 'Chat Room'), ('email', 'Email')], default='chat', max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, max_length=1200, null=True)),
                ('object_type', models.CharField(choices=[('vehicle', 'Vehicle Review'), ('mechanic', 'Mechanic'), ('support_ticket', 'Support Ticket')], max_length=200)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('awaiting-user', 'Awaiting Customer Response'), ('resolved', 'Resolved')], max_length=20)),
                ('severity_level', models.CharField(choices=[('high', 'High Severity'), ('low', 'Low Severity'), ('moderate', 'Moderate Severity')], max_length=20)),
                ('subject', models.CharField(max_length=400)),
                ('correspondents', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to='feedback.chatmessage')),
                ('tags', models.ManyToManyField(blank=True, to='feedback.tag')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.ticketcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.supportticket'),
        ),
    ]
