# Generated by Django 5.1.1 on 2025-12-04 10:30

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('chat', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('communication', 'Communication'), ('support', 'Support'), ('service-delivery', 'Service Delivery'), ('car-quality', 'Car Quality'), ('car-cleanliness', 'Car Cleanliness')], max_length=200)),
                ('stars', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ticket Category',
                'verbose_name_plural': 'Ticket Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=1200, null=True)),
                ('object_type', models.CharField(choices=[('vehicle', 'Vehicle Review'), ('dealer', 'Dealership Review'), ('mechanic', 'Mechanic'), ('support_ticket', 'Support Ticket'), ('purchase', 'Car Purchase'), ('service', 'Service')], max_length=200)),
                ('related_object', models.UUIDField(blank=True, null=True)),
                ('related_order', models.UUIDField(blank=True, null=True)),
                ('ratings', models.ManyToManyField(blank=True, related_name='review_ratings', to='feedback.rating')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_items', to='feedback.review'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('awaiting-user', 'Awaiting Customer Response'), ('resolved', 'Resolved')], max_length=20)),
                ('severity_level', models.CharField(choices=[('high', 'High Severity'), ('low', 'Low Severity'), ('moderate', 'Moderate Severity')], max_length=20)),
                ('subject', models.CharField(max_length=400)),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_chat', to='chat.chatroom')),
                ('correspondents', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='accounts.customer')),
                ('tags', models.ManyToManyField(blank=True, related_name='ticket_tags', to='feedback.tag')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_tickets', to='feedback.ticketcategory')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=350)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email Notification'), ('in-app', 'In-App Notification'), ('sms', 'SMS Notification')], default='in-app', max_length=10)),
                ('cta_text', models.CharField(blank=True, max_length=20, null=True)),
                ('cta_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user'], name='feedback_no_user_id_2c0b54_idx'), models.Index(fields=['read'], name='feedback_no_read_313331_idx'), models.Index(fields=['level'], name='feedback_no_level_4b49b9_idx'), models.Index(fields=['channel'], name='feedback_no_channel_27b8de_idx'), models.Index(fields=['date_created'], name='feedback_no_date_cr_11dc80_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='feedback_re_reviewe_cc9eed_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['object_type'], name='feedback_re_object__8adb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['related_object'], name='feedback_re_related_f5a810_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['related_order'], name='feedback_re_related_aa77b5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['date_created'], name='feedback_re_date_cr_f15351_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['reviewId'], name='feedback_ra_reviewI_1a33ad_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['area'], name='feedback_ra_area_c3a5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['stars'], name='feedback_ra_stars_a384c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('reviewId', 'area')},
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer'], name='feedback_su_custome_e7e4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='feedback_su_status_56d246_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['severity_level'], name='feedback_su_severit_e05139_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='feedback_su_categor_1e4339_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['date_created'], name='feedback_su_date_cr_82096d_idx'),
        ),
    ]
