# Generated by Django 5.1.1 on 2026-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email Notification'), ('in-app', 'In-App Notification'), ('sms', 'SMS Notification'), ('push', 'Push Notification')], default='in-app', max_length=10),
        ),
    ]
