# Generated by Django 5.1.1 on 2024-09-13 13:52

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/attachments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='messages',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='correspondents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='feedback.chatattachments'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.CharField(choices=[('sales-chat', 'Chat Room'), ('support-chat', 'Support Room')], default='sales-chat', max_length=200)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to='feedback.chatmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='feedback.chatroom'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=350)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email Notification'), ('in-app', 'In-App Notification'), ('sms', 'SMS Notification')], default='in-app', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
