# Generated by Django 5.1.1 on 2026-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_notification_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='cta_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
