# Generated by Django 6.0.3 on 2026-03-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_notification_cta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratings',
        ),
    ]
