# Generated by Django 5.1.1 on 2024-09-11 15:00

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('listing_type', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'customer'}, related_name='viewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('rental', 'Car Rental'), ('sale', 'Car Sale')], max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=3)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=3, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=10.0, max_digits=3)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order_items', models.ManyToManyField(blank=True, to='rentals.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('last_rented', models.DateTimeField(max_length=200)),
                ('available', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('current_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.carrental')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.vehiclecategory')),
                ('tags', models.ManyToManyField(blank=True, to='rentals.vehicletag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.vehicle'),
        ),
    ]
