# Generated by Django 5.1.1 on 2024-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_rented',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
