# Generated by Django 5.1.1 on 2024-09-12 17:58

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_vehicle_last_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='vehicles/images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='rentals.vehicleimage'),
        ),
    ]
