# Generated by Django 5.1.1 on 2024-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_vehicle_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=21367.0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=23435.0, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='title',
            field=models.CharField(blank=True, default='Hey Test', max_length=400, null=True),
        ),
    ]
