# Generated by Django 5.1.1 on 2024-09-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_vehicle_rental_price_vehicle_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='title',
            new_name='listing_title',
        ),
    ]
