# Generated by Django 5.1.1 on 2024-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_carrental_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_uk', 'Used (UK)'), ('used_ng', 'Used (Nigerian)'), ('used_be', 'Used (Belgium)')], default='used_uk', max_length=20),
        ),
    ]
