# Generated by Django 5.1.1 on 2024-09-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_vehicle_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
