# Generated by Django 5.1.1 on 2024-09-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_listing_rental_price_alter_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=10000),
            preserve_default=False,
        ),
    ]
