# Generated by Django 5.1.1 on 2024-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_order_commission_alter_vehicle_listing_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
