# Generated by Django 5.1.1 on 2024-09-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_listing_rental_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='commission',
        ),
    ]
