# Generated by Django 5.1.1 on 2024-09-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('feedback', '0001_initial'),
        ('rentals', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='rentals.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='feedback.rating'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_history',
            field=models.ManyToManyField(blank=True, related_name='service_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='rentals.listing'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='feedback.rating'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='feedback.rating'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='rentals.vehicle'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='location',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_job', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='job_history',
            field=models.ManyToManyField(blank=True, related_name='job_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='feedback.rating'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='services',
            field=models.ManyToManyField(blank=True, to='bookings.serviceoffering'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='otp',
            name='valid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.order'),
        ),
    ]
