# Generated by Django 5.1.1 on 2025-02-28 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('feedback', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='listings.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_history',
            field=models.ManyToManyField(blank=True, related_name='service_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='billing_info',
            field=models.ManyToManyField(blank=True, to='accounts.billinginformation'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='feedback.review'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='listings.vehicle'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='documents',
            field=models.ManyToManyField(blank=True, to='accounts.document'),
        ),
        migrations.AddField(
            model_name='customer',
            name='documents',
            field=models.ManyToManyField(blank=True, to='accounts.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, to='accounts.file'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='billing_info',
            field=models.ManyToManyField(blank=True, to='accounts.billinginformation'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_job', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='documents',
            field=models.ManyToManyField(blank=True, to='accounts.document'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='job_history',
            field=models.ManyToManyField(blank=True, related_name='job_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='feedback.review'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='services',
            field=models.ManyToManyField(blank=True, to='bookings.serviceoffering'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp',
            name='valid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payout_info',
            field=models.ManyToManyField(blank=True, to='accounts.payoutinformation'),
        ),
    ]
