# Generated by Django 5.1.1 on 2024-10-26 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_history',
            field=models.ManyToManyField(blank=True, related_name='service_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='billing_info',
            field=models.ManyToManyField(blank=True, to='accounts.billinginformation'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.listing'),
        ),
    ]
