# Generated by Django 5.1.1 on 2025-12-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('bookings', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_history',
            field=models.ManyToManyField(blank=True, related_name='customer_service_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='billing_info',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_billing', to='accounts.billinginformation'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='dealership_listings', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='dealership_orders', to='listings.order'),
        ),
    ]
