# Generated by Django 5.1.1 on 2025-12-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('bookings', '0001_initial'),
        ('feedback', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='dealership_reviews', to='feedback.review'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='dealership_vehicles', to='listings.vehicle'),
        ),
        migrations.AddField(
            model_name='businessverificationsubmission',
            name='dealership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_submission', to='accounts.dealership'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_documents', to='accounts.document'),
        ),
        migrations.AddField(
            model_name='customer',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_documents', to='accounts.document'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='accessed_by',
            field=models.ForeignKey(help_text='User who accessed the document', on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='submission',
            field=models.ForeignKey(help_text='The verification submission being accessed', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='accounts.businessverificationsubmission'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='accounts_fi_name_02b9c2_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='document_files', to='accounts.file'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealership',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_locations', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_locations', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_locations', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='billing_info',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_billing', to='accounts.billinginformation'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mechanic', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_documents', to='accounts.document'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='job_history',
            field=models.ManyToManyField(blank=True, related_name='mechanic_job_history', to='bookings.servicebooking'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_locations', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='mechanic_reviews', to='feedback.review'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='mechanic_services', to='bookings.serviceoffering'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessverificationsubmission',
            name='mechanic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_submission', to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='mechanicboost',
            name='mechanic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boosted', to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='custom_recipients',
            field=models.ManyToManyField(blank=True, help_text='Select specific users to receive this newsletter', related_name='newsletter_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp',
            name='valid_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='payout_info',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_profiles', to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='payout_info',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_profiles', to='accounts.payoutinformation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payout_info',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_profiles', to='accounts.payoutinformation'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user_type'], name='accounts_ac_user_ty_36af62_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['provider'], name='accounts_ac_provide_ceab20_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['verified_email'], name='accounts_ac_verifie_1a8d45_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounts_ac_is_acti_b52bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_staff'], name='accounts_ac_is_staf_648b11_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['date_joined'], name='accounts_ac_date_jo_37209b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['api_token'], name='accounts_ac_api_tok_601930_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['welcome_email_sent_at'], name='accounts_ac_welcome_48a846_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['submission', 'document_type'], name='accounts_do_submiss_32c622_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['accessed_by', 'date_created'], name='accounts_do_accesse_8d5a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['access_type'], name='accounts_do_access__7d6bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['ip_address'], name='accounts_do_ip_addr_772aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['success'], name='accounts_do_success_f296ab_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['date_created'], name='accounts_do_date_cr_147c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='accounts_do_owner_i_bb9177_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doctype'], name='accounts_do_doctype_91e5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['user'], name='accounts_lo_user_id_2c90c4_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['country', 'state'], name='accounts_lo_country_d869d6_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='accounts_lo_city_d9049c_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['lat', 'lng'], name='accounts_lo_lat_9ee2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginformation',
            index=models.Index(fields=['user'], name='accounts_bi_user_id_490a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginformation',
            index=models.Index(fields=['is_primary'], name='accounts_bi_is_prim_49a7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationsubmission',
            index=models.Index(fields=['business_type'], name='accounts_bu_busines_dd86f5_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationsubmission',
            index=models.Index(fields=['status'], name='accounts_bu_status_ab9303_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationsubmission',
            index=models.Index(fields=['migrated_to_cloudinary'], name='accounts_bu_migrate_cf959f_idx'),
        ),
        migrations.AddIndex(
            model_name='businessverificationsubmission',
            index=models.Index(fields=['reviewed_at'], name='accounts_bu_reviewe_f88ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicboost',
            index=models.Index(fields=['mechanic'], name='accounts_me_mechani_db96f1_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicboost',
            index=models.Index(fields=['start_date', 'end_date'], name='accounts_me_start_d_092f69_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicboost',
            index=models.Index(fields=['active'], name='accounts_me_active_f9cd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['valid_for', 'channel', 'used'], name='accounts_ot_valid_f_729644_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code', 'used'], name='accounts_ot_code_a59b31_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose', 'channel'], name='accounts_ot_purpose_b0af38_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['date_created'], name='accounts_ot_date_cr_d1731a_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutinformation',
            index=models.Index(fields=['user'], name='accounts_pa_user_id_94a669_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutinformation',
            index=models.Index(fields=['channel'], name='accounts_pa_channel_68a1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutinformation',
            index=models.Index(fields=['account_number'], name='accounts_pa_account_705a20_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['user'], name='accounts_me_user_id_f1bd65_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['business_name'], name='accounts_me_busines_eb83c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['slug'], name='accounts_me_slug_9138c3_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['level'], name='accounts_me_level_63488c_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['available'], name='accounts_me_availab_ee8dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['verified_business'], name='accounts_me_verifie_6095dd_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['business_type'], name='accounts_me_busines_33836e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['user'], name='accounts_de_user_id_044a57_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['business_name'], name='accounts_de_busines_cc57ca_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['slug'], name='accounts_de_slug_fb6596_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['level'], name='accounts_de_level_f66994_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['verified_business'], name='accounts_de_verifie_9bb48c_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['offers_rental', 'offers_purchase'], name='accounts_de_offers__9a123b_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['cac_number'], name='accounts_de_cac_num_34eebb_idx'),
        ),
        migrations.AddIndex(
            model_name='dealership',
            index=models.Index(fields=['tin_number'], name='accounts_de_tin_num_481fff_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='accounts_cu_user_id_4678a9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['verified_phone_number'], name='accounts_cu_verifie_56b950_idx'),
        ),
    ]
