# Generated by Django 5.1.1 on 2024-09-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_image_agent_image_customer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.CharField(default='customer', max_length=20),
            preserve_default=False,
        ),
    ]
