# Generated by Django 5.1.1 on 2024-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer Account'), ('dealer', 'Car Dealer'), ('mech', 'Mechanic')], default='staff', max_length=20),
        ),
    ]
