# Generated by Django 5.1.1 on 2024-09-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_api_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'One Time Pin (OTP)', 'verbose_name_plural': 'One Time Pins (OTPs)'},
        ),
    ]
