# Generated by Django 5.1.1 on 2024-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_history',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
