# Generated by Django 5.1.1 on 2024-09-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='wallet',
        ),
    ]
