# Generated by Django 5.1.1 on 2024-09-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_user_type'),
        ('accounts', '0004_remove_wallet_owner'),
    ]

    operations = [
    ]
