# Generated by Django 5.1.1 on 2024-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Agent'), ('customer', 'Customer'), ('dealer', 'Car Dealer'), ('mechanic', 'Mechanic')], default='customer', max_length=20),
        ),
    ]
