# Generated by Django 5.1.1 on 2024-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customer_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
