# Generated by Django 5.1.1 on 2026-02-11 02:03

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_referral_code_account_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=5000.0, help_text='Amount to reward the referrer', max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='Currency of the reward', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable the referral program')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum purchase amount required to trigger reward', max_digits=10)),
            ],
            options={
                'verbose_name': 'Referral Setting',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_ref', models.CharField(blank=True, help_text='Reference of the qualifying transaction', max_length=100, null=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_triggered', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
