# Generated by Django 5.1.1 on 2024-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_wallet_alter_dealer_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='customer',
            name='verified_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealer',
            name='verified_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='verified_phone_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Agent'), ('customer', 'Customer'), ('dealer', 'Car Dealer'), ('mech', 'Mechanic')], default='customer', max_length=20),
        ),
    ]
