# Generated by Django 5.1.1 on 2026-02-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fcmdevice'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_verified'], name='accounts_ac_is_veri_2a91e4_idx'),
        ),
    ]
