# Generated by Django 5.1.1 on 2026-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='dealership',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area', max_length=200, null=True, verbose_name='LGA'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
    ]
