# Generated by Django 5.1.1 on 2024-09-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MottaWalletEmail',
            new_name='MotaaWalletEmail',
        ),
    ]
