# Generated by Django 6.0.3 on 2026-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_related_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
