# Generated by Django 5.1.1 on 2026-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('charge', 'Wallet Charge'), ('payment', 'Payment'), ('adjustment', 'Admin Adjustment')], default='deposit', max_length=30),
        ),
    ]
