# Generated by Django 5.1.1 on 2026-01-19 08:57

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_account_verified_email'),
        ('listings', '0002_uav'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRevenueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dealer_percentage', models.DecimalField(decimal_places=2, default=60.0, help_text='Percentage of inspection fee that goes to the dealer (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('platform_percentage', models.DecimalField(decimal_places=2, default=40.0, help_text='Percentage of inspection fee that goes to the platform (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings record can be active at a time')),
                ('effective_date', models.DateTimeField(auto_now_add=True, help_text='When these settings became effective')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this revenue split configuration', null=True)),
            ],
            options={
                'verbose_name': 'Inspection Revenue Settings',
                'verbose_name_plural': 'Inspection Revenue Settings',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['is_active'], name='inspections_is_acti_01e6a8_idx'), models.Index(fields=['effective_date'], name='inspections_effecti_9f1a1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('inspection_number', models.CharField(blank=True, help_text='Unique inspection slip number (e.g., INSP-7)', max_length=20, null=True, unique=True)),
                ('inspection_type', models.CharField(choices=[('pre_purchase', 'Pre-Purchase Inspection'), ('pre_rental', 'Pre-Rental Inspection'), ('maintenance', 'Maintenance Inspection'), ('insurance', 'Insurance Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('signed', 'Signed'), ('archived', 'Archived')], default='pending_payment', max_length=20)),
                ('overall_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('inspection_slip', cloudinary.models.CloudinaryField(blank=True, help_text='PDF slip for customer to show dealer', max_length=255, null=True, verbose_name='inspection_slip')),
                ('inspection_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Inspection fee amount', max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (wallet, bank)', max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('exterior_data', models.JSONField(blank=True, default=dict)),
                ('interior_data', models.JSONField(blank=True, default=dict)),
                ('engine_data', models.JSONField(blank=True, default=dict)),
                ('mechanical_data', models.JSONField(blank=True, default=dict)),
                ('safety_data', models.JSONField(blank=True, default=dict)),
                ('documentation_data', models.JSONField(blank=True, default=dict)),
                ('inspector_notes', models.TextField(blank=True, null=True)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inspections', to='accounts.customer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_inspections', to='accounts.dealership')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_payments', to='wallet.transaction')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='listings.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Inspection',
                'verbose_name_plural': 'Vehicle Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRevenueSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total inspection fee paid', max_digits=10)),
                ('dealer_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to dealer wallet', max_digits=10)),
                ('dealer_percentage', models.DecimalField(decimal_places=2, help_text='Percentage used for dealer calculation', max_digits=5)),
                ('dealer_credited', models.BooleanField(default=False, help_text='Whether dealer wallet has been credited')),
                ('dealer_credited_at', models.DateTimeField(blank=True, help_text='When dealer wallet was credited', null=True)),
                ('platform_amount', models.DecimalField(decimal_places=2, help_text='Amount retained by platform', max_digits=10)),
                ('platform_percentage', models.DecimalField(decimal_places=2, help_text='Percentage used for platform calculation', max_digits=5)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_revenue_splits', to='wallet.transaction')),
                ('revenue_settings', models.ForeignKey(help_text='Revenue settings used for this split', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_splits', to='inspections.inspectionrevenuesettings')),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_split', to='inspections.vehicleinspection')),
            ],
            options={
                'verbose_name': 'Inspection Revenue Split',
                'verbose_name_plural': 'Inspection Revenue Splits',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('exterior_front', 'Exterior - Front View'), ('exterior_rear', 'Exterior - Rear View'), ('exterior_left', 'Exterior - Left Side'), ('exterior_right', 'Exterior - Right Side'), ('interior_dashboard', 'Interior - Dashboard'), ('interior_seats', 'Interior - Seats'), ('engine_bay', 'Engine Bay'), ('tires_wheels', 'Tires and Wheels'), ('damage_detail', 'Damage Detail'), ('documents', 'Vehicle Documents'), ('other', 'Other')], max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='inspection_photo')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.vehicleinspection')),
            ],
            options={
                'verbose_name': 'Inspection Photo',
                'verbose_name_plural': 'Inspection Photos',
                'ordering': ['category', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('standard', 'Standard Report'), ('detailed', 'Detailed Report'), ('legal', 'Legal Compliance Report')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready for Signature'), ('signed', 'Fully Signed'), ('archived', 'Archived')], default='generating', max_length=20)),
                ('document_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='inspection_document')),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('include_photos', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('compliance_standards', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inspections.vehicleinspection')),
            ],
            options={
                'verbose_name': 'Inspection Document',
                'verbose_name_plural': 'Inspection Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Minimum withdrawal amount: ₦100', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
                ('account_name', models.CharField(blank=True, default='', help_text='Account holder name (verified with Paystack)', max_length=200)),
                ('account_number', models.CharField(blank=True, default='', help_text='Bank account number', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank name', max_length=200)),
                ('bank_code', models.CharField(blank=True, default='', help_text='Bank code for Paystack', max_length=10)),
                ('paystack_verified', models.BooleanField(default=False, help_text='Whether account details were verified with Paystack')),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack transfer recipient code', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('inspector', 'Inspector'), ('customer', 'Customer'), ('dealer', 'Dealer Representative')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('signature_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signature')),
                ('signature_method', models.CharField(blank=True, choices=[('drawn', 'Hand Drawn'), ('typed', 'Typed Name'), ('uploaded', 'Uploaded Image')], max_length=20, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, null=True)),
                ('signature_coordinates', models.JSONField(blank=True, default=dict)),
                ('signature_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_signatures', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='inspections.inspectiondocument')),
            ],
            options={
                'verbose_name': 'Digital Signature',
                'verbose_name_plural': 'Digital Signatures',
                'ordering': ['role', '-signed_at'],
                'indexes': [models.Index(fields=['document'], name='inspections_documen_58f46b_idx'), models.Index(fields=['signer'], name='inspections_signer__bffe03_idx'), models.Index(fields=['role'], name='inspections_role_8d56fc_idx'), models.Index(fields=['status'], name='inspections_status_dc1edf_idx'), models.Index(fields=['signed_at'], name='inspections_signed__ac121c_idx')],
                'unique_together': {('document', 'signer', 'role')},
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('standard', 'Standard Template'), ('detailed', 'Detailed Template'), ('legal', 'Legal Compliance Template'), ('custom', 'Custom Template')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='inspections/templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('supports_photos', models.BooleanField(default=True)),
                ('supports_recommendations', models.BooleanField(default=True)),
                ('compliance_standards', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='inspections_categor_ee9898_idx'), models.Index(fields=['is_active'], name='inspections_is_acti_005818_idx'), models.Index(fields=['created_by'], name='inspections_created_7371a0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['vehicle'], name='inspections_vehicle_6b740b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['inspector'], name='inspections_inspect_51ff81_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['customer'], name='inspections_custome_6a5a68_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['dealer'], name='inspections_dealer__088e77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['inspection_type'], name='inspections_inspect_ef6150_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['status'], name='inspections_status_0d50e2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['inspection_date'], name='inspections_inspect_857a65_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrevenuesplit',
            index=models.Index(fields=['inspection'], name='inspections_inspect_dede69_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrevenuesplit',
            index=models.Index(fields=['payment_transaction'], name='inspections_payment_88c416_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrevenuesplit',
            index=models.Index(fields=['dealer_credited'], name='inspections_dealer__41b3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrevenuesplit',
            index=models.Index(fields=['date_created'], name='inspections_date_cr_8bffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['inspection'], name='inspections_inspect_521340_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['category'], name='inspections_categor_b4092f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondocument',
            index=models.Index(fields=['inspection'], name='inspections_inspect_48834c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondocument',
            index=models.Index(fields=['status'], name='inspections_status_851bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondocument',
            index=models.Index(fields=['generated_at'], name='inspections_generat_39037e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondocument',
            index=models.Index(fields=['expires_at'], name='inspections_expires_2502fb_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user'], name='inspections_user_id_c99174_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet'], name='inspections_wallet__a15c79_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='inspections_status_5bdc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['date_created'], name='inspections_date_cr_37f305_idx'),
        ),
    ]
