# Generated by Django 5.1.1 on 2026-02-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the inspection is scheduled', null=True),
        ),
    ]
