# Generated by Django 5.1.1 on 2026-03-13 00:00

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_vehicleinspection_dealer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pre_purchase_fee', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('pre_rental_fee', models.DecimalField(decimal_places=2, default=30000.0, max_digits=10)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=25000.0, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=40000.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inspection Fee Setting',
                'verbose_name_plural': 'Inspection Fee Settings',
            },
        ),
    ]

