# Generated by Django 5.1.1 on 2026-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_date_of_birth_dealership_date_of_birth_and_more'),
        ('inspections', '0004_inspectionfeesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inspections', to='accounts.customer'),
        ),
    ]
