# Generated by Django 5.1.1 on 2025-01-28 08:53

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400, unique=True)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('emergency', 'Emergency Assistance'), ('routine', 'Routine Check')], default='routine', max_length=20)),
                ('booking_status', models.CharField(choices=[('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('requested', 'Requested')], default='requested', max_length=20)),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('responded_on', models.DateTimeField(blank=True, null=True)),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=utils.make_UUID)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('charge_rate', models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Hourly Rate')], default='flat', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
