# Generated by Django 5.1.1 on 2025-12-04 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_initial'),
        ('bookings', '0001_initial'),
        ('chat', '__first__'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='client_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_feedback', to='feedback.review'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_conversation', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_bookings', to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='bookings.service'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_bookings', to='bookings.serviceoffering'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['offered_by'], name='bookings_se_offered_d0e2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['service'], name='bookings_se_service_7697ee_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['charge_rate'], name='bookings_se_charge__6d0587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceoffering',
            unique_together={('offered_by', 'service')},
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['customer'], name='bookings_se_custome_581883_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['mechanic'], name='bookings_se_mechani_ac13bf_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['booking_status'], name='bookings_se_booking_2e6a53_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['type'], name='bookings_se_type_4a951d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['completed'], name='bookings_se_complet_f01600_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['date_created'], name='bookings_se_date_cr_bbb75d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['started_on'], name='bookings_se_started_bfca77_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['ended_on'], name='bookings_se_ended_o_12d8a8_idx'),
        ),
    ]
