# Generated by Django 5.1.1 on 2025-01-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('bookings', '0001_initial'),
        ('chat', '__first__'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='client_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.review'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mechanic'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='services',
            field=models.ManyToManyField(blank=True, to='bookings.serviceoffering'),
        ),
    ]
