# Generated by Django 5.1.1 on 2024-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_servicebooking_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_delivery',
        ),
    ]
