# Generated by Django 5.1.1 on 2024-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_servicebooking_service_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='type',
            field=models.CharField(choices=[('emergency', 'Emergency Assistance'), ('routine', 'Routine Check')], default='routine', max_length=20),
        ),
    ]
